<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Sklad2.BLL\Sklad2.BLL.csproj" />
    <ProjectReference Include="..\..\Sklad2.Core\Sklad2.Core.csproj" />
    <ProjectReference Include="..\..\Sklad2.DAL\Sklad2.DAL.csproj" />
    <ProjectReference Include="..\Sklad2.WEB.Client\Sklad2.WEB.Client.csproj" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.4" />
  </ItemGroup>

</Project>
